version: "3.8"
services:
  palworld:
    build:
      context: .
    volumes:
      - ./server:/server
    ports:
        - "8211:8211"
    restart: unless-stopped
    command: ["/server/PalServer.sh", "-useperfthreads", "-NoAsyncLoadingThread", "-UseMultithreadForDS"]

networks: {}
