version: "3.8"
services:
  palworld:
    build:
      context: .
    volumes:
      - ./server:/server
    user: "1000"
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    restart: unless-stopped
    command:
      - /server/PalServer.sh
      - -useperfthreads
      - -NoAsyncLoadingThread
      - -UseMultithreadForDS
      - EpicApp=PalServer
networks: {}
