version: "3.8"
services:
  palworld:
    build:
      context: .
    volumes:
      - ./server:/server
    ports:
        - "6587:6587"
    restart: unless-stopped
    command: ["/server/PalServer.sh"]

networks: {}